import ItchIo from "@/components/projects/sections/itch-io";

export const name = "Froilan Zarate Jr";
export const fullName = "Froilan Danganan Zarate Jr";
export const email = "zarate_rj@yahoo.com";
export const phone = "+1 (408) 600-9717";
export const locations = ["Milpitas, CA", "Vallejo, CA"];

export const links = {
    github: "https://github.com/rjzarate",
    linkedin: "https://www.linkedin.com/in/froilan-zarate-jr-computer-scientist/",
    email: "mailto:" + email,
};

export const images = {
    profile: "/img/profile.jpeg",
    profile1: "/img/profile1.jpg",
    hobbiesDND: "/img/hobbies/dnd.jpg",
    hobbiesOutside: "/img/hobbies/outside.jpg",
    hobbiesPoker: "/img/hobbies/poker.jpg",
    hobbiesCosplay: "/img/hobbies/cosplay.jpg",
};

/**
 * List of projects -
 * bug tracker
 */

export const projects = [
    {
        id: "portfolio-website",
        title: "Portfolio Website",
        ranking: 20,
        shortDescription: "My portfolio website built with Next.js and Tailwind CSS",
        description:
            "A responsive portfolio website built with Next.js and Tailwind CSS to showcase my work and skills.",
        image: "/img/projects/portfolio-website/main.png",
        technologies: ["React", "Next.js", "Tailwind CSS", "TypeScript", "v0", "GitHub"],
        demoUrl: "https://example.com",
        githubUrl: "https://github.com/rjzarate/website-portfolio",
        category: "Web Development",
        duration: "1 week (Jul. 2025)",
        startDate: "2025-07-17",
        endDate: "2025-07-22",
        teamSize: "Solo project",
        challenges: ["User-friendliness & styling", "Clean code design patterns", "Project descriptions"],
        detailedDescription:
            "My second personal website designed as a portfolio to showcase my skills and projects. Used Vercel's v0 to develop the base of the website, and integrated some of my own styling and components. I wanted to create this portfolio in a short amount of time so I can use it to apply for jobs; thus, I've decided to implement everything in React rather than following a 3-tier architecture design pattern — though you can see many of my semester-long school projects use this pattern.",
        problemStatement:
            "There's only so much a resume can show and many job applications have an entry to upload your website. Additionally, I need a better way to create a \"brand\" for myself and a better way to display what I've worked on.",
        solution:
            "So, why not only create a website that displays who I am and what I've done, but also learn more about React! Many website generators like Wix and Squarespace exist, but they don't provide the flexibility and learning experience that building from scratch does.",
        features: [
            "Project search",
            "Page navigation",
            "Side navigation",
            "Dark mode",
            "Mobile view",
            "Adaptive projects",
        ],
        featureDescriptions: [
            "Search for projects by title, description, or technology.",
            "Navigate through different sections of the portfolio easily.",
            "A side navigation bar that adapts to the current section.",
            "Dark mode toggle for better user experience.",
            "Mobile view for accessibility on smaller screens.",
            "Displayed as sections, projects are easily customizable.",
        ],
        results: [
            "I now have a portfolio 😎",
            "Compared to my resume, increased my project descriptions by over 200%",
            "Added 5+ images to each project compared to LinkedIn and other Job Boards",
        ],
        lessonsLearned:
            "Having a good portfolio is really important, as it's YOUR way of showing how you want others to see yourself. With a good portfolio, it is possible to include everything that you've done without making it overwhelming by having features like \"Featured Projects\" and a search bar.",
        contributions: undefined,
    },
    {
        id: "banking-application",
        title: "Banking Application",
        shortDescription: "A web-based banking application for Google users",
        description:
            "Software Engineering course final project. Designed with the 3-tier architecture software design pattern.",
        detailedDescription:
            "This full-stack web banking application was the final project for my Software Engineering course. The project followed the 3-tier architecture model, separating concerns between the presentation layer (React/Next.js frontend), the logic layer (Flask API), and the data layer (MySQL database). We used Docker to ensure a consistent development. The application allows users to log in using Google OAuth, view their balance and transaction history, make payments via an automatic billing system, and upload checks for processing. Admin users have access to a custom dashboard for user monitoring and management. Throughout the development process, we coordinated using Agile methodologies, conducting weekly sprints and stand-ups to track progress.",
        image: "/img/projects/banking-application/main.png",
        technologies: [
            "React",
            "Flask",
            "MySQL",
            "Docker",
            "Next.js",
            "Agile",
            "Scrum Meetings",
            "Google OAuth",
            "TypeScript",
            "Python",
            "Tailwind CSS",
            "v0",
            "Database",
            "GitHub",
        ],
        demoUrl: "https://youtu.be/5uQTpoYigDU",
        githubUrl: "https://github.com/Jjmaxxx/onlinebanking",
        youtubeVideoId: "5uQTpoYigDU",
        category: "Full-Stack",
        duration: "4 months (Feb. 2025 – May 2025)",
        startDate: "2025-02",
        endDate: "2025-05",
        teamSize: "4 developers",
        challenges: ["Small team size", "Work delegation", "API calls"],
        problemStatement:
            "A new online-only bank is being launched and it requires a web-based application server, mobile application, and seamless integration to handle all the banking transactions and financial planning tools.",
        solution: undefined,
        solutions: [
            "Support opening, closing, and transferring accounts, as well as cash deposits and withdrawals via both online platform and physical ATMs of other banks.",
            "Enable mobile check deposits through image capture and ensure a user-friendly interface accessible to all age demographics.",
            "Allow users to create accounts using a valid email and password, and manage savings, checking, deposits, and other financial tools.",
            "Integrate a Chase ATM locator with map support and redirection to external mapping services such as Apple Maps and Google Maps.",
            "Automate bill payments, fund transfers, balance updates, fraud alerts, and generation of scheduled financial reports.",
            "Implement a manager dashboard for monitoring fraud, generating reports, ensuring compliance, and enabling admins to query customer accounts and activities.",
            "Use Flask for the backend, ReactJS for a cross-platform frontend, integrate Google Maps, generate sample data for demo, and collaborate through GitHub with version control and team contributions.",
        ],
        features: [
            "Google OAuth login",
            "Automatic billing",
            "Admin dashboard",
            "ATM API",
            "Chase ATM locator",
            "Check upload",
        ],
        featureDescriptions: [
            "Login using Google OAuth for secure authentication.",
            "Automatic billing system for recurring payments.",
            "Admin dashboard for managing users and transactions.",
            "ATM API integration for real-time ATM data.",
            "Chase ATM locator for finding nearby ATMs.",
            "Users can upload a check and the server can check for validity and amount.",
        ],
        gallery: undefined,
        results: [
            "Easy user login by using a Google account",
            "1 line installation; lightweight and fast compared to other groups",
            "97% grade on Final Project; finished in time when all other groups had 6 members",
        ],
        lessonsLearned: undefined,
        contributions: [
            "User logout and user authentication",
            "Created working Docker containers for the frontend, backend, and database",
            "Developed the backend for the Admin dashboard",
        ],
    },
    {
        id: "ai-battles",
        title: "AI Battles",
        ranking: 90,
        shortDescription: "A prompt-based fantasy game using Flask and Google Gemini",
        description:
            "Advanced Programming with Python Final Project. Input a unique repsonse to defeat AI generated enemies.",
        detailedDescription:
            "This project was created use Python Flask as the frontend and backend, and uses Google Gemini to control the enemy generation in addition to win and lose condition. This project was created in essentially one day, (you can view the commit history on GitHub), but was able to be unique and complex enough to get a 100% in the project 😎. When creating this project, I followed as closely to the 3-tier architecture design pattern, with having 3 scripts: application.py (frontend), director.py (backend), and the ai.py (generator). I am honestly really proud on how fast I coded the entire project, but do wish I could have expanded more on it.",
        image: "/img/projects/ai-battles/main.png",
        technologies: ["Flask", "Python", "Google Gemini", "AI"],
        demoUrl: undefined,
        githubUrl: "https://github.com/rjzarate/Python-Game",
        category: "AI Integration",
        duration: "2 days (Dec. 2024)",
        startDate: "2024-12-1",
        endDate: "2024-12-2",
        teamSize: "2 developers",
        challenges: ["AI token limits", "AI prompts"],
        problemStatement: undefined,
        solution: undefined,
        solutions: undefined,
        features: ["AI integration", "Unique enemies", "Limitless solves"],
        featureDescriptions: [
            "Uses AI to control many features of the gameplay.",
            "Fight different fantasy-generated enemies that get harder as time goes on.",
            "Use your imagination to defeat your enemies.",
        ],
        results: ["100% grade on Final Project"],
        lessonsLearned:
            "This gave me and my partner a better understanding on how we should structure our prompts when using AI. A lot of the times, it would give a giant response or would use too many tokens to the point you can only fight one enemy before having to wait until we get more tokens. There has to be a balance between giving just enough to the AI and making sure that the AI gives the proper response.",
        contributions: undefined,
    },
    {
        id: "3d-shader-sceneviewer",
        title: "3D Shader Sceneviewer",
        shortDescription: "A sceneviewer created with C++ openFrameworks that can export rendered images and obj files",
        description: "Introduction to Computer Graphics course final project.",
        detailedDescription:
            "This project was created using C++ openFrameworks, and was a culmination of many of the labs and smaller projects I've done during that class. I wanted to combine many of the features that the labs and projects had, with the addition of having the ability to export the entire scene into a .obj file. So, I merged and refactored a lot of the code to make everything work into one project. Additionally, I had to research how .obj and .mtl files work, as these are both separate files but connect with each other to render the .obj file's material, diffuse, normals, specular, and ambient occlusion.",
        image: "/img/projects/3d-shader-sceneviewer/main.png",
        technologies: ["C++", "openFrameworks", "Computer Graphics", "Lighting", "Shading", "obj"],
        demoUrl: "https://youtu.be/if9lEYg0YGY",
        githubUrl:
            "https://github.com/rjzarate/school-projects/tree/main/school_classes/cs134/of_v0.12.0_osx_release/apps/myApps/project_3_planar_textures",
        youtubeVideoId: "if9lEYg0YGY",
        category: "3D Graphics",
        duration: "3 months (Oct. 2024 – Dec. 2024)",
        startDate: "2024-10",
        endDate: "2024-12",
        teamSize: "Solo project",
        challenges: ["Shader algorithms", "Objects to .obj"],
        problemStatement:
            'The current project can only export rendered images, but cannot be used into a "real" 3D editor to modify.',
        solution: "Have a way to export the entire scene as a .obj file so that it can be uploaded to a 3D editor.",
        solutions: undefined,
        features: ["3D sceneviewer", "Render images with shading", "Export to obj"],
        featureDescriptions: [
            "Can interact with the objects and move them in the scene",
            "Can render the scene with the given lighting and textures.",
            "Can export the entire scene as a .obj, .mtl, and it's corresponding texture files.",
        ],
        gallery: [
            "/img/projects/3d-shader-sceneviewer/main.png",
            "/img/projects/3d-shader-sceneviewer/poster.png",
            "/img/projects/3d-shader-sceneviewer/img.png",
        ],
        results: ["Professor enjoyed my presentation 😎", "100% grade on Final Project"],
        lessonsLearned:
            "This project gave me a great understanding on how .obj files work, as I basically had to write the entire .obj file and .mtl file myself.",
        contributions: undefined,
    },
    {
        id: "cinket",
        title: "Cinket",
        shortDescription: "My D&D website for my players / Password: Limitless",
        description: "Contains everything needed for my players to understand my world and create their characters.",
        detailedDescription:
            "In July 2024, I got into being a Dungeon Master for D&D and started creating my world: Cinket. Instead of keeping all of my notes and idea on a Google Document, I decided to use a note-taking application called Obsidian. What made me able to host my first D&D session on August 2024 was being able to upload all of my notes into a working website! All of my players are able to use this website and can reference it when creating their characters or have questions about the world of Cinket. I eventually kept expanding myh Obsidian notes, which inturn expanded my website to essentially be a D&D 5.5e wiki. I've decided to add password authentication for distribution purposes, but currently, the password is: Limitless.",
        image: "/img/projects/cinket/main.png",
        technologies: ["JavaScript", "Markdown", "Obsidian", "Dataview", "Digital Garden", "GitHub"],
        demoUrl: "https://cinket.com/",
        githubUrl: undefined,
        category: "Full-Stack",
        duration: "9+ Months (Aug. 2024 – Current)",
        startDate: "2024-09",
        endDate:
            new Date(Date.now()).getFullYear().toString() +
            "-" +
            (new Date(Date.now()).getMonth().toString() < 10
                ? "0" + new Date(Date.now()).getMonth().toString()
                : new Date(Date.now()).getMonth().toString()),
        teamSize: "1 developer",
        challenges: ["Limited API", "Page organization", "API calls"],
        problemStatement: "My players needed a better way to access a lot of homebrew and lore in the world of Cinket.",
        solution: undefined,
        solutions: undefined,
        features: ["Password authentication", "Search bar", "Side navigation", "Dataview tables", "Markdown to HTML"],
        featureDescriptions: [
            "Uses Octauthent for password authentication to limit users and protect data.",
            "Advanced search bar that can search within the pages.",
            "Collapsing folder structure and pages.",
            "Uses JavaScript and Dataview to display spells and tables.",
            "Converts Obsidian's Markdown to HTML, allowing for easy editing and hyperlinking.",
        ],
        gallery: [
            "/img/projects/cinket/main.png",
            "/img/projects/cinket/home.png",
            "/img/projects/cinket/authentication.png",
        ],
        results: [
            "My 10+ players use this instead of other D&D wikis",
            "Used in ALL of my sessions during Dungeon Mastering",
            "50,000+ words of months of ongoing development on the world and game mechanics.",
        ],
        lessonsLearned:
            "Since I am using an Obsidian extension to convert the md files to HTML, it's very limited compared to building a website from Next.js and other React frameworks.",
        contributions: undefined,
    },
    {
        id: "sharesphere-application",
        title: "ShareSphere Application",
        ranking: 85,
        shortDescription: "A web-based application for hobbists to share and keep track of items",
        description:
            "Introduction to Database Management Systems course final project. Designed with the 3-tier architecture software design pattern.",
        detailedDescription: "",
        image: "/img/projects/sharesphere-application/main.png",
        technologies: ["React", "MySQL", "Docker", "Node.js", "JavaScript", "JSON", "Database", "GitHub"],
        demoUrl: "https://youtu.be/9IalyFeNDjM",
        githubUrl: undefined,
        youtubeVideoId: "9IalyFeNDjM",
        category: "Full-Stack",
        duration: "2 months (Apr. 2024 – May 2024)",
        startDate: "2024-04",
        endDate: "2024-05",
        teamSize: "5 developers",
        challenges: ["Learning web development", "Work delegation", "API calls"],
        detailedDescription:
            "This project aims to develop a web application that facilitates item sharing among hobbyists within local groups. The app will allow users to create personal libraries of their collectible items like books, puzzles, and board games. Members of the same group can view each other's libraries and request to borrow desired items, eliminating the need to purchase duplicates. This project was my first time learning JavaScript, React, and Docker. I spent a lot of time learning these applications, which although I could not contribute as much as I wish I could have, I did learn a lot from this project.",
        problemStatement:
            "Hobbists and local groups are having trouble sharing and allocating their collectible items like books, puzzles, and board games.",
        solution: undefined,
        solutions: [
            "The core features include a member library view displaying the user's personal collections; a group member view listing individuals in each of the user's groups; and an integrated calendar for tracking events as well as deadlines for returning borrowed items. Users will be able to register accounts and log in to access the app's functionalities.",
            "Central to the application is the ability for group members to send borrow requests to each other for specific items in their libraries. Users can create and attend events, which are associated with particular groups. Crucial to enabling library sharing is a privacy control mechanism allowing users to selectively share entire libraries or individual items with each of their groups.",
            'The app will incorporate a search function to locate available and borrowable items within a group\'s pooled collections. Potential additional features include gifting items between users, duplicating existing item entries, creating "friends" lists to view multiple libraries, reminder notifications, and user blocking options.',
            "From a non-functional perspective, the app will prioritize security through email/OAuth authentication and anti-spam measures, as well as portable responsive design for the web. Accessibility standards will be followed, along with optimizations for reasonable performance and load times.",
        ],
        features: ["Database security", "Library privacy control", "Calendar integration"],
        featureDescriptions: [
            "SQL injection protection implementation.",
            "Make and browse libraries; privacy settings to make them public or private.",
            "Create and view events within your different groups and libraries.",
        ],
        gallery: undefined,
        results: ["Working connection between database, backend, and frontend", "87% Final Project grade"],
        lessonsLearned: undefined,
        contributions: ["User & group page", "SQL mock data & testing"],
    },
    {
        id: "k4t",
        title: "K4T",
        ranking: 24,
        shortDescription: "A Unity2D game where a cat must defeat bosses to save the world!",
        description: "Game Development Club project. Uses only one button for all the controls; works on mobile.",
        image: "/img/projects/k4t/main.png",
        technologies: ["Unity", "C#", "GitHub Workflow", "Producer", "Project Management", "Animation", "GitHub"],
        demoUrl: "https://froilan-zarate.itch.io/k4t",
        githubUrl: "https://github.com/rjzarate/k4t/",
        category: "Game Development",
        duration: "4 months (Feb. 2024 – May 2024)",
        startDate: "2024-02",
        endDate: "2024-05",
        teamSize: "9 programmers, 5 artists, 4 game designers",
        challenges: ["Workload delegation", "Programmer-Artist-GD communication", "Scope creep"],
        detailedDescription:
            "K4T was a game I created on Scratch in 2017, and I wanted to make it a reality and code it in game engine. I gathered many of the programmers and artists from Solace and we worked on K4T for the 2024 Spring semester. During the development process, I was the producer and lead programmer to make sure everything went smoothly. The gameplay revolves on a vertical screen where you control the cat's movements and attack with only one button; this way, we can easily make this game for mobile devices. We experienced many road blocks that hindered our progress, so our main vision couldn't be completed in one semester, but we were still able to create a functional game and upload it itch.io.",
        itchIo: {
            title: "K4T",
            description: "Everything is one button! Defeat the evil bosses from above!",
            embedUrl: "https://itch.io/embed/2788238",
            gameUrl: "https://froilan-zarate.itch.io/k4t",
        },
        problemStatement: undefined,
        solution: undefined,
        features: ["1 button controls", "2 bosses", "10+ different boss attacks", "Animation, particles, music & SFX"],
        featureDescriptions: [
            "Move, shoot, and change directions with one click of the button!",
            "Fight the Meat-eor and Cheese Mouse UFO to save the Moon!",
            "Unique boss attack patterns that challenges the player's movement.",
            "Small details that make the game feel alive.",
        ],
        gallery: [
            "/img/projects/k4t/gameplay.png",
            "/img/projects/k4t/gameplay1.png",
            "/img/projects/k4t/gameplay2.png",
            "/img/projects/k4t/gameplay3.png",
            "/img/projects/k4t/poster.png",
            "/img/projects/k4t/main.png",
            "/img/projects/k4t/cat-sheet.png",
            "/img/projects/k4t/cheese-ufo-sheet.png",
            "/img/projects/k4t/crashed-ufo.png",
        ],
        results: [
            "I now made a game in my favorite game 😎",
            "Connected with many old high school friends and still keep in touch",
        ],
        lessonsLearned:
            "When I pitched this project, I believed that we could do 8 bosses and 4 worlds. However, as a beginner producer and beginner game developers, it was difficult to complete many of the deadlines in time. Nonetheless, I am still happy for how the gameplay turned out and may even pick this game up to finish it.",
        contributions: undefined,
    },
    {
        id: "color-me-extension",
        title: "Color Me Extension",
        ranking: 100,
        shortDescription: "An extension that changes the color of your tab bar",
        description: "Programming Paradigms course final project. Built with React",
        detailedDescription: "",
        image: "/img/projects/color-me-extension/main.png",
        technologies: ["React", "Yarn", "Extension", "JSON", "GitHub"],
        githubUrl: "https://github.com/ehcaw/colorme",
        category: "Full-Stack",
        duration: "2 months (Apr. 2024 – May 2024)",
        startDate: "2024-04",
        endDate: "2024-05",
        teamSize: "2 developers",
        challenges: ["Learning React", "Browser integration"],
        detailedDescription:
            "This project uses React to create a universal web extension that can change the color of your tabs. Additionally, it can change the color depending on your theme or depending on saved websites. This project was my first time learning TypeScript and React. I spent a lot of time learning these applications, which although I could not contribute as much as I wish I could have, I did learn a lot from this project.",
        problemStatement: undefined,
        solution: undefined,
        solutions: undefined,
        features: ["Tab bar color", "Previously colors", "Website colors"],
        featureDescriptions: [
            "Change your tab bar to your desired color.",
            "Saves the five most recent colors you picked in case you want to go back to them.",
            "Have specific colors that you want for certain websites.",
        ],
        gallery: undefined,
        results: ["95% Final Project grade"],
        lessonsLearned: undefined,
        contributions: ["Saved colors", "Website saving themes"],
    },
    {
        id: "bug-tracker",
        title: "Bug Tracker",
        ranking: 99,
        shortDescription: "An application to track and report bugs for projects",
        description: "Object-Oriented Design course final project. Built with JavaFX.",
        detailedDescription: "",
        image: "/img/projects/bug-tracker/main.png",
        technologies: ["Java", "JavaFX", "CSS", "GitHub"],
        githubUrl: "https://github.com/FardinHaque60/Bug-Base",
        category: "Full-Stack",
        duration: "5 months (Aug. 2023 – Dec. 2023)",
        startDate: "2023-08",
        endDate: "2023-12",
        teamSize: "3 developers",
        challenges: ["Website styling"],
        detailedDescription:
            "This project uses JavaFX to create the frontend of the desktop application. The application allows the user to create projects. These projects can then have tickets which can be bugs or certain aspects of the project, which then these tickets can have comments within them. A big part of this project was implementing good coding practices and design patterns, as our Object-Oriented Design course focused on relationships like inheritance, dependecy, and aggregation. We've also develop functional and technical spec documents, and created UML diagrams for our project.",
        problemStatement:
            "A survey of 950 developers found that most of them spend more than 25% of their time fixing bugs. (Vizard 1) Fixing bugs is essential for a software to stay functional and live longer, so having a bug tracker is a helpful tool. However, many trackers are open to the public, which could leak the data of private projects. So, this software should allow the user to input certain information regarding the project and its bugs without the information being exposed to the public. This software should allow users to be more productive and have an easy to access repositories for all their tasks on a projects to-do list. Additionally, this software should be open-source and a free desktop application with no ads.",
        solution: undefined,
        solutions: [
            "Software displays a homepage to user when launched. Home Screen allows users to navigate through existing projects, create project, search for existing projects, and create a ticket.",
            "The software allows the user to create new projects. User can specify project name, date, and description. The software allows the user to edit existing projects fields. The software allows the user to search for existing projects. The software allows the user to delete projects.",
            "The software allows the user to create new tickets within a project. User can specify ticket name and description. Timestamp is generated for ticket. The software allows the user to edit existing tickets within a project. Timestamp will change for ticket. The software allows the user to search for existing tickets within a project. User can search for tickets through ticket name or project ticket lives in. User can delete tickets. Timestamp will change for ticket.",
            "User can create comments underneath tickets descriptions and timestamps. User can edit / delete these timestamps in the view ticket page.",
        ],
        features: ["Project creation", "Ticket (Bug) creation", "Comments"],
        featureDescriptions: [
            "Change your tab bar to your desired color.",
            "Saves the five most recent colors you picked in case you want to go back to them.",
            "Have specific colors that you want for certain websites.",
        ],
        gallery: undefined,
        results: ["92% Final Project grade"],
        lessonsLearned: undefined,
        contributions: ["Bug creation", "Code maintenance", "Error statements"],
    },
    {
        id: "catch-bobo",
        title: "Catch Bobo",
        ranking: 25,
        shortDescription: "A Cat-and-Mouse multiplayer minigame within Minecraft",
        description: "A Minecraft 1.20 map with custom classes, textures, and abilities.",
        image: "/img/projects/catch-bobo/main.png",
        technologies: ["mcfunction", "Blockbench", "JSON"],
        demoUrl: "https://www.youtube.com/watch?v=YKfC8Mfxz0k",
        githubUrl: "https://github.com/rjzarate/Catch-Bobo/",
        youtubeVideoId: "YKfC8Mfxz0k",
        category: "Game Development",
        duration: "7 months (Aug. 2022 – Feb. 2023)",
        startDate: "2022-08",
        endDate: "2023-02",
        teamSize: "1 developer (Me), 2 artists, 5+ builders",
        challenges: ["Multiplayer integration", "3D modeling", 'Making it "fun"', "Scope creep"],
        detailedDescription:
            "This is my biggest Minecraft project that involved a lot of designing and problem solving due to mcfunction's limited logic capabilities. I worked on this projects with a few of my high school friends. Funny enough, the game \"Catch Bobo \" was one of my friend's Minecraft minigame they made in middle school, and I wanted to make it a full-fledged game with custom textures and coded abilities. So, my friends and I gathered together to work on this project; I would do all of the coding and game design, while my friends would work on the map and help playtest the abilities. As the project progressed, I asked another friend who knows 3D modeling to help me learn Blockbench, which is a 3D modeling software for Minecraft and other low-poly games.",
        problemStatement: undefined,
        solution: undefined,
        features: [
            "10+ custom characters",
            "50+ unique abilities",
            "25+ Custom 3D models and textures",
            "Expansive map with unique landmarks",
            "Adjustable game settings",
        ],
        featureDescriptions: [
            "Each class has their own gimmick that makes them fun to play.",
            "Different abilities that go beyond survival vanilla Minecraft.",
            "Unique 3D models and textures to make the characters feel powerful.",
            "Can easily change the game timer, ability cooldowns, and objectives.",
            "640x640 block map with different biomes and buildings.",
        ],
        gallery: [
            "/img/projects/catch-bobo/poster.png",
            "/img/projects/catch-bobo/map.png",
            "/img/projects/catch-bobo/map1.png",
            "/img/projects/catch-bobo/gameplay.png",
            "/img/projects/catch-bobo/gameplay1.png",
            "/img/projects/catch-bobo/gameplay2.png",
        ],
        results: [
            "I now made a game in my favorite game 😎",
            "Connected with many old high school friends and still keep in touch",
        ],
        lessonsLearned:
            "This is one of my longest projects that took to finish, which is mainly due to how big the map is and wanting to add more characters and textures. I'm happy with the result of this project, but also wish I spent less time working on it by having a clear goal.",
        contributions: undefined,
    },
    {
        id: "soulace",
        title: "Soulace",
        ranking: 98,
        shortDescription: "A Unity2D game where you use souls to defeat monsters and save the town",
        description: "Game Development Club project. Puzzle-grid turn-based story game.",
        image: "/img/projects/soulace/main.png",
        technologies: ["Unity", "C#", "Producer", "Project Management", "GitHub"],
        demoUrl: "https://a-fam.itch.io/soulace",
        githubUrl: "https://github.com/pham-t-alex/Block-Action",
        category: "Game Development",
        duration: "5 months (Aug. 2022 – Dec 2022)",
        startDate: "2022-08",
        endDate: "2022-12",
        teamSize: "6 programmers, 7 artists",
        challenges: ["Workload delegation", "Game design", "Scope creep"],
        detailedDescription:
            "A game designed around the concept of fitting blocks into a grid + turn-based strategy combat. This is my first ever big project that I did in school! Since this was when I just started to learn how to program, I decided to take the role on delegating workload, presenting our progress to the club, and hosting meetings to make sure everything was on track.",
        itchIo: {
            title: "Soulace",
            description:
                "A game designed around the concept of fitting blocks into a grid + turn-based strategy combat.",
            embedUrl: "https://itch.io/embed/1815503",
            gameUrl: "https://a-fam.itch.io/soulace",
        },

        problemStatement: undefined,
        solution: undefined,
        features: [
            "Complex grid patterns",
            "Unique monsters",
            "Increasing difficulty",
            "Animation, particles, music & SFX",
        ],
        featureDescriptions: [
            "Use the souls you gathered to cast abilities against your enemies!",
            "Fight monsters that mechanically challege you to adapt.",
            "Go through 8 different levels and a boss battle!",
            "Small details that make the game feel alive.",
        ],
        gallery: [
            "/img/projects/soulace/main.png",
            "/img/projects/soulace/background.png",
            "/img/projects/soulace/trello.png",
            "/img/projects/soulace/gameplay.png",
            "/img/projects/soulace/gameplay1.png",
            "/img/projects/soulace/gameplay2.png",
        ],
        results: ["Game is finished with 5+ levels"],
        lessonsLearned: undefined,
        contributions: [
            "Delegated workload for the programmer and art team",
            "Created 5+ timelines that display the work schedule",
            "Main presentation speaker during progress reports",
        ],
    },
];
